
// Alg Data (Case Name, Blind and Reg Alg Notation) 
const algCornerCases = ["ULB-URB (AB)",
"ULB-ULF (AD)",
"ULB-LFU (AF)", 
"ULB-LDF (AG)", 
"ULB-LBD (AH)", 
"ULB-FUL (AI)", 
"ULB-FDR (AK)", 
"ULB-FLD (AL)",
"ULB-RBU (AN)", 
"ULB-RDB (AO)",
"ULB-RFD (AP)", 
"ULB-BUR (AQ)", 
"ULB-BDL (AS)",
"ULB-BDR (AT)", 
"ULB-DFL (AU)",
"ULB-DFR (AV)",
"ULB-DBR (AW)",
"ULB-DBL (AX)"];

const algEdgeCases = [ "UR-UB (BA)", 
"UR-UL (BD)", 
"UR-LU (BE)", 
"UR-LF (BF)",
"UR-LD (BG)",
"UR-LB (BH)",
"UR-FR (BJ)", 
"UR-FD (BK)", 
"UR-FL (BL)",
"UR-RB (BN)", 
"UR-RD (BO)",
"UR-RF (BP)", 
"UR-BU (BQ)",
"UR-BL (BR)",
"UR-BD (BS)",
"UR-BR (BT)",
"UR-DF (BU)",
"UR-DR (BV)",
"UR-DB (BW)",
"UR-DL (BX)",

"UL-UB (DA)", 
"UL-UR (DB)",
"UL-LF (DF)",
"UL-LD (DG)",
"UL-LB (DH)",
"UL-FR (DJ)",
"UL-FD (DK)",
"UL-FL (DL)",
"UL-RU (DM)",
"UL-RB (DN)", 
"UL-RD (DO)",
"UL-RF (DP)",
"UL-BU (DQ)",
"UL-BL (DR)",
"UL-BD (DS)",
"UL-BR (DT)",
"UL-DF (DU)",
"UL-DR (DV)",
"UL-DB (DW)",
"UL-DL (DX)",

"LU-UB (EA)",
"LU-UR (EB)",
"LU-LF (EF)",
"LU-LD (EG)",
"LU-LB (EH)",
"LU-FR (EJ)",
"LU-FD (EK)",
"LU-FL (EL)",
"LU-RU (EM)",
"LU-RB (EN)",
"LU-RD (EO)",
"LU-RF (EP)",
"LU-BU (EQ)",
"LU-BL (ER)",
"LU-BD (ES)",
"LU-BR (ET)",
"LU-DF (EU)",
"LU-DR (EV)",
"LU-DB (EW)",
"LU-DL (EX)",

"LF-UB (FA)",
"LF-UR (FB)",
"LF-UL (FD)",
"LF-LU (FE)",
"LF-LD (FG)",
"LF-LB (FH)",
"LF-FR (FJ)",
"LF-FD (FK)",
"LF-RU (FM)",
"LF-RB (FN)",
"LF-RD (FO)",
"LF-RF (FP)",
"LF-BU (FQ)",
"LF-BL (FR)",
"LF-BD (FS)",
"LF-BR (FT)",
"LF-DF (FU)",
"LF-DR (FV)",
"LF-DB (FW)",
"LF-DL (FX)",

"LD-UB (GA)",
"LD-UR (GB)",
"LD-UL (GD)",
"LD-LU (GE)",
"LD-LF (GF)",
"LD-LB (GH)",
"LD-FR (GJ)",
"LD-FD (GK)",
"LD-FL (GL)",
"LD-RU (GM)",
"LD-RB (GN)",
"LD-RD (GO)",
"LD-RF (GP)",
"LD-BU (GQ)",
"LD-BL  (GR)",
"LD-BD  (GS)",
"LD-BL (GT)",
"LD-DF  (GU)",
"LD-DR (GV)",
"LD-DR (GW)"]

const regAlgos = ["Lw' U R' D2 R U' R' D2' R Lw", 
"R' D' R U2 R' D R U R' D' R U' U2' R' D R", 
"F U2 R' D' R U2' R' D R F'", 
"R' D R U2 R' D' R U2'", 
"U' R D' R' U2 R D R' U2' U", 
"Lw' U2 R' D2 R U2' R' D2' R Lw", 
"D' R' D R U2 R' D' R U2' D", 
"D' U' R D' R' U2 R D R' U2' U D", 
"R D R' R' D2 R U2 R' D2' R U2' R D' R'", 
"U' R D R' U2 R D' R' U2' U", 
"R' D' R U2 R' D R U2'", 
"R' D' U2 R' D R U2' R' D' R D R", 
"R' D2 R U2 R' D2' R U2'", 
"D U' R D' R' U2 R D R' U2' U D'", 
"R F' R' U' R D R' U2 R D' R' U2' U R F R'", 
"D R D' R' R' D R U2 R' D' R U2' R D R' D'", 
"R D' R' R' D R U2 R' D' R U2' R D R'", 
"R' z R' R' D R U2 R' D' R U2' R z' R"];

const bldAlgos = ["[Lw': [U, R' D2 R]]", 
"[R' D' R U2: [R' D R, U]]", 
"[F: [U2, R' D' R]]", 
"[R' D R, U2]", 
"[U': [R D' R', U2]]", 
"[Lw': [U2, R' D2 R]]", 
"[D': [R' D R, U2]]", 
"[D' U': [R D' R', U2]]", 
"[R D R': [R' D2 R, U2]]", 
"[U': [R D R', U2]]", 
"[R' D' R, U2]", 
"[R' D': [U2, R' D R]]", 
"[R' D2 R, U2]", 
"[D U': [R D' R', U2]]", 
"[R F' R' U': [R D R', U2]]", 
"[D R D' R': [R' D R, U2]]", 
"[R D' R': [R' D R, U2]]", 
"[R' z R': [R' D R, U2]]"];

const cllAlgs = ["R U R' U R U2 R'",
"(F R' F' R) U2 R U2 R'",
"(U2) R U' R U' R' U R' U' F R' F'",
"(U2) R U R' U (R' F R F') R U2 R'",
"R U' R' (F R' F' R)",
"R' F2 R U2 R U' R' F", 
"R' U' R U' R' U2 R",
"(U2) F' R U R' U2 R' F2 R",
"(U2) R U2 R' U2 R' F R F'",
"R U2 R' F R' F' R U' R U' R'",
"(U2) R' F R F' R U R'",
"R2 F R U2 R U' R' U2 F' R",
"(R U R' U') (R' F R F')",
"(U) F U' R U2 R' U' F2 R U R'",
"(U') F (R U R' U') R U' (R' U' R U) R' F'",
"F R F' R U R' U' R' / (U2) L' U' L U L F' L' F",
"(U') R' U R' U2 R U2 R' U R2 U' R'",
"(U) R' U R U2 R2 F R F' R",
"(U') F R U R' U' F' / (U) F U R U' R' F'",
"(U2) F R U R' U2 F' R U' R' F",
"R U' R2 F R F' R U R' U' R U R' U'",  
"(U2) R U R2' U' R U2 R' U2' R U' R",
"x R U' R U' R' U L' U' L x2",
"R' U (R' F R F') R U2 (R' U R)",
"(U) F' (R U R' U') R' F R / F R U' (R' U' R U) R' F'",
"R U2 R2 F R F' R U2 R'",
"(U') R U' R' U R U' R' F R' F' R2 U R'",
"(F R' F' R) (U R U' R')",
"(U) R' U R' U2 R U' R' U R U' R2",
"R U2 R' F' R U2 R' U R' F2 R",
"F (R U R' U') (R U R' U') F'",
"R U' R' F R' F R U R' F R",
"R U2 R' U2 R' F R2 U R' U' F'",
"(U') R' U' R' F R F' R U' R' U2 R",
"(U') R U' R U' R' U R' F R2 F'",
"R' F2 R F' U2 R U' R' U' F",
"R2 U2 R U2 R2",
"x' U2 R U2 R2 F2 R U2 x",
"(U') R U R' U R U (R' F R' F') R",
"(U') F R2 U' R2 U' R2 U R2 F'"];

//205, 211, 218, 223, 229, 235
const cllNames = ["Sune", "Anti-Sune", "Charmeleon / T", "Superman / U", "Pi", "Double Sune / H"];